// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pri.Ca.Infrastructure.Data;

#nullable disable

namespace Pri.Ca.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    [Migration("20230224140147_Sales")]
    partial class Sales
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CategoryGame", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("GamesId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "GamesId");

                    b.HasIndex("GamesId");

                    b.ToTable("CategoryGame");

                    b.HasData(
                        new
                        {
                            CategoriesId = 1,
                            GamesId = 1
                        },
                        new
                        {
                            CategoriesId = 2,
                            GamesId = 1
                        },
                        new
                        {
                            CategoriesId = 3,
                            GamesId = 1
                        },
                        new
                        {
                            CategoriesId = 1,
                            GamesId = 2
                        },
                        new
                        {
                            CategoriesId = 3,
                            GamesId = 2
                        },
                        new
                        {
                            CategoriesId = 2,
                            GamesId = 2
                        },
                        new
                        {
                            CategoriesId = 1,
                            GamesId = 3
                        },
                        new
                        {
                            CategoriesId = 2,
                            GamesId = 3
                        });
                });

            modelBuilder.Entity("Pri.Ca.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kids"
                        });
                });

            modelBuilder.Entity("Pri.Ca.Core.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fifa2000"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Wolfenstein"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Minecraft"
                        });
                });

            modelBuilder.Entity("Pri.Ca.Core.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            GameId = 2,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 3,
                            GameId = 3,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 4,
                            GameId = 1,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 5,
                            GameId = 2,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 6,
                            GameId = 3,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 7,
                            GameId = 1,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 8,
                            GameId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 9,
                            GameId = 3,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 10,
                            GameId = 1,
                            Quantity = 13
                        },
                        new
                        {
                            Id = 12,
                            GameId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 13,
                            GameId = 3,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 14,
                            GameId = 1,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 15,
                            GameId = 2,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 16,
                            GameId = 3,
                            Quantity = 23
                        },
                        new
                        {
                            Id = 17,
                            GameId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 18,
                            GameId = 2,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 19,
                            GameId = 3,
                            Quantity = 9
                        },
                        new
                        {
                            Id = 20,
                            GameId = 1,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 21,
                            GameId = 2,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 22,
                            GameId = 3,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 23,
                            GameId = 1,
                            Quantity = 9
                        },
                        new
                        {
                            Id = 24,
                            GameId = 2,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 25,
                            GameId = 3,
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("CategoryGame", b =>
                {
                    b.HasOne("Pri.Ca.Core.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pri.Ca.Core.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pri.Ca.Core.Entities.Sale", b =>
                {
                    b.HasOne("Pri.Ca.Core.Entities.Game", "Game")
                        .WithMany("Sales")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Pri.Ca.Core.Entities.Game", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
